name: COVID_US
channels:
  - conda-forge
dependencies:
  - absl-py=0.10.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.10
  - click=8.0.3
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flit-core=3.6.0
  - fonttools=4.28.5
  - freetype=2.10.4
  - frozenlist=1.2.0
  - future=0.18.2
  - gast=0.4.0
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.43.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - ipykernel=6.6.1
  - ipython=7.31.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - jsonschema=4.3.3
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - keras=2.7.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclient=0.5.9
  - nbconvert=6.4.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - ninja=1.10.2
  - notebook=6.4.6
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - progressbar=2.5
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - prompt_toolkit=3.0.24
  - protobuf=3.18.1
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.8
  - scipy=1.7.3
  - send2trash=1.8.0
  - six=1.15.0
  - sleef=3.5.1
  - sqlite=3.37.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-deps=2.7.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - traitlets=5.1.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - werkzeug=2.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - beautifulsoup4==4.10.0
    - chromedriver==2.24.1
    - flatbuffers==2.0
    - fsspec==2022.1.0
    - grad-cam==1.3.7
    - h11==0.12.0
    - ipython-genutils==0.2.0
    - joblib==1.1.0
    - libclang==12.0.0
    - numpy==1.22.0
    - opencv-python==4.5.5.62
    - outcome==1.1.0
    - pandas==1.3.5
    - pydeprecate==0.3.1
    - pytorch-lightning==1.5.9
    - pytz==2021.3
    - pyyaml==6.0
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - selenium==4.1.0
    - setuptools==59.5.0
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - tensorflow-estimator==2.7.0
    - tensorflow-macos==2.7.0
    - tensorflow-metal==0.3.0
    - threadpoolctl==3.0.0
    - torchmetrics==0.7.0
    - torchvision==0.11.3
    - tornado==6.1
    - tqdm==4.62.3
    - trio==0.19.0
    - trio-websocket==0.9.2
    - ttach==0.0.3
    - vimeo-downloader==0.3.3
    - webencodings==0.5.1
    - wsproto==1.0.0
